#!/usr/bin/env node

const fs = require("node:fs/promises");
const path = require("node:path");

const iconsDir = __dirname;
const generatedDir = path.join(iconsDir, "generated");
const manifestPath = path.join(iconsDir, "manifest.json");

async function main() {
  const manifest = await readManifest();
  await fs.mkdir(generatedDir, { recursive: true });
  await cleanGeneratedFiles();

  const exports = [];
  for (const iconName of manifest) {
    const svg = await fetchIcon(iconName);
    const source = parseSvg(iconName, svg);
    const identifier = toIdentifier(iconName);
    const fileName = `${iconName}.js`;
    const filePath = path.join(generatedDir, fileName);
    await fs.writeFile(filePath, renderModule(identifier, source, iconName), "utf8");
    exports.push(`export { default as ${identifier} } from "./generated/${fileName}";`);
  }

  const indexPath = path.join(iconsDir, "index.js");
  await fs.writeFile(indexPath, `${exports.join("\n")}\n`, "utf8");
}

async function readManifest() {
  const raw = await fs.readFile(manifestPath, "utf8");
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed) || parsed.some((value) => typeof value !== "string")) {
    throw new Error("ui/icons/manifest.json must be a string array");
  }
  return parsed;
}

async function cleanGeneratedFiles() {
  const entries = await fs.readdir(generatedDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }
    if (!entry.name.endsWith(".js")) {
      continue;
    }
    await fs.unlink(path.join(generatedDir, entry.name));
  }
}

async function fetchIcon(iconName) {
  const url = `https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/${iconName}.svg`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`failed to fetch ${url}: HTTP ${response.status}`);
  }
  return response.text();
}

function parseSvg(iconName, svg) {
  const match = /<svg[^>]*>([\s\S]*?)<\/svg>/.exec(svg);
  if (!match) {
    throw new Error(`invalid svg for ${iconName}`);
  }

  const body = match[1].trim();
  const nodes = [];
  const tagPattern = /<([a-zA-Z][\w:-]*)([^>]*)\/>/g;
  for (const tag of body.matchAll(tagPattern)) {
    const name = tag[1];
    const rawAttributes = tag[2] ?? "";
    nodes.push([name, parseAttributes(rawAttributes)]);
  }

  if (nodes.length === 0) {
    throw new Error(`no svg nodes found for ${iconName}`);
  }

  return nodes;
}

function parseAttributes(raw) {
  const attributes = {};
  const pattern = /([:@a-zA-Z0-9_-]+)="([^"]*)"/g;
  for (const match of raw.matchAll(pattern)) {
    attributes[match[1]] = match[2];
  }
  return attributes;
}

function toIdentifier(iconName) {
  return iconName
    .split("-")
    .map((part, index) => {
      if (index === 0) {
        return part;
      }
      return part.slice(0, 1).toUpperCase() + part.slice(1);
    })
    .join("");
}

function renderModule(identifier, source, iconName) {
  return `// Generated by ui/icons/sync.js from https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/${iconName}.svg\nexport const ${identifier} = ${JSON.stringify({ name: iconName, contents: source }, null, 2)};\nexport default ${identifier};\n`;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
